Inventario/Models/Bienes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;



namespace Inventario.Models
{
    public class Bienes
    {
        //Atributos
        [Key]
        public string numeroDePatrimonio { get; set; }//llave primaria

        [Required]
        public string codigoDeBarras { get;  set; }

         [StringLength(30)]
        public string descripcion { get; set; }
       
        public string anadidoPor { get; set; }//Llave foranea

        [Required]
        public string numeroDeFactura { get;  set; }//llave foranea

        public string ley { get; set; }

        [StringLength(20)]
        public string marca { get; set; }

        [StringLength(20)]
        public string modelo { get; set; }

        [StringLength(20)]
        public string serie { get; set; }

    
        public int IDEspecialidad { get; set; }

        //LlaveForanea
        [ForeignKey("IDEspecialidad")]
        public virtual Especialidad Especialidad { get; set; }


        [StringLength(3)]
        public string ubicacion { get; set; }

        [Required]
        public EstadosEnum estado { get;  set; }

        [Required]
        public CondicionesEnum condicion { get;  set; }

        //Metodos constructores
        public Bienes()
        {
            numeroDePatrimonio = "CIF000";
            codigoDeBarras = "11111111";
            descripcion = "No especificado";
            anadidoPor = "Desconocido";
            numeroDeFactura = "No especificado";
            ley = "0000";
            marca = "Desconocido";
            modelo = "Desconocido";
            serie = "0000";
            IDEspecialidad= 1;
            ubicacion = "C-0";
            estado = estado = EstadosEnum.Excelente;
            condicion = condicion = CondicionesEnum.Activo;
        }
    }
}

Inventario/ViewModels/VerBienesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Inventario.Models;

namespace Inventario.ViewModels
{
    public class VerBienesViewModel
    {
        public string numeroDePatrimonio { get; set; }//llave primaria       
        public string codigoDeBarras { get; set; }
        public string descripcion { get; set; }
        public string anadidoPor { get; set; }//Llave foranea
        public string numeroDeFactura { get; set; }//llave foranea
        public string ley { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public int IDEspecialidad { get; set; }
        public string ubicacion { get; set; }
        public EstadosEnum estado { get; set; }
        public CondicionesEnum condicion { get; set; }

        public Especialidad Especialidad { get; set; }


      
     

       
     

        
        

        

    }
}

Inventario/Controllers/BienesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Inventario.Models;
using Inventario.Services;
using Inventario.ViewModels;

namespace Inventario.Controllers
{
    public class BienesController : Controller
    {
        private Filtrador filtro = new Filtrador();
        private ApplicationDbContext db = new ApplicationDbContext();
        private BienesRepository repositorio = new BienesRepository();//Objeto que proporcionara los datos provenientes de la BD
        private TempRepository tempRepositorio = new TempRepository();

        //Accion para ver bienes
        public ActionResult BuscarVerBienes(string id)
        {
            List<Bienes> lista = new List<Bienes>();
      
            if (id == "")
            {
                lista = repositorio.obtenerBienesActivos();
                return View("VerBienes",lista);
            }
            else
            {
                Bienes bien = new Bienes();
                bien = repositorio.buscarBien(id);
                if (bien == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    lista.Add(bien);
                    return View("VerBienes", lista);
                }
            }
        }


    public ActionResult RestablecerLista()
        {
            List<Bienes> lista = new List<Bienes>();
            lista = repositorio.obtenerBienesActivos();
            return View("VerBienes",lista);
        }


    public ActionResult VerBienes()
        {
            List<Bienes> bienesSinFiltrar = repositorio.obtenerTodosLosBienes();
            var model = filtro.filtrarBienesAcivos(bienesSinFiltrar);//Extrae solamente los bienes activos
            return View(model);
        }

        //Acciones para anadir Bienes
        public ActionResult AnadirBienes()
        {
            //Este viewbag contiene los datos necesarios para que funcione  adecuadamente el DropDownList
            ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnadirBienes([Bind(Include = "numeroDePatrimonio,codigoDeBarras,descripcion,anadidoPor,numeroDeFactura,ley,marca,modelo,serie,idEspecialidad,ubicacion,estado,condicion")] Bienes bienes)
        {
            if (ModelState.IsValid)
            {
                repositorio.anadirBien(bienes);
            }
            ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad", bienes.IDEspecialidad);
            return View(bienes);
        }

        //Acciones Para Actualizar
        [ValidateAntiForgeryToken]
        public ActionResult BuscarBien(string id)
        {
            if (id == "")
            {
                ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad");
                return RedirectToAction("ActualizarBienes");
            } else
            {
                Bienes bien = repositorio.buscarBien(id);
                if (bien == null)
                {
                    return HttpNotFound();
                }
                ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad", bien.IDEspecialidad);
              
                return View("ActualizarBienes", bien);
            }
        }
        //Accion GetRequest
        [HttpGet]
        public ActionResult ActualizarBienes()
        {
            ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad");
            return View();
        }
        //Accion Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ActualizarBienes([Bind(Include = "numeroDePatrimonio,codigoDeBarras,descripcion,anadidoPor,numeroDeFactura,ley,marca,modelo,serie,idEspecialidad,ubicacion,estado,condicion")] Bienes bienes)
        {
            if (ModelState.IsValid)
            {
                repositorio.actualizarBien(bienes);
                return RedirectToAction("VerBienes");
            }
            ViewBag.IDEspecialidad = new SelectList(db.Especialidad, "ID", "nombreEspecialidad", bienes.IDEspecialidad);
            return View(bienes);
        }

        //Acciones para Dar de baja
        [ValidateAntiForgeryToken]
        public ActionResult BuscarDarBaja(string id)
        {  
            if (id == "")
            {
                return RedirectToAction("DarBaja");
            }
            else
            {
                Bienes bien = repositorio.buscarBien(id);
                if (bien == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    tempRepositorio.anadirBienTemp(bien);
                    List<Bienes>bienesDarBaja= tempRepositorio.extraerData();
                    return View("DarBaja",bienesDarBaja);
                }
            }
        }

        // List<Bienes> bienesDarBaja = new List<Bienes>();
        [HttpGet]
        public ActionResult DarBaja()
        {

            tempRepositorio.limpiar();


            return View("DarBaja");
        }
 
        [HttpPost]
        public ActionResult DarBaja(List<Bienes> bienes)
        {

          List<Bienes> lista =  tempRepositorio.extraerData();
     
            repositorio.darDeBaja(lista);
            
            //var model = bienesDarBaja;   bienesDarBaja
            return View();
        }

        // GET: Bienes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bienes bienes = db.Bienes.Find(id);
            if (bienes == null)
            {
                return HttpNotFound();
            }
            return View(bienes);
        }

        // POST: Bienes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Bienes bienes = db.Bienes.Find(id);
            db.Bienes.Remove(bienes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Inventario/Views/Bienes/ActualizarBienes.cshtml
@model Inventario.Models.Bienes
@using Inventario.Models
@{
    ViewBag.Title = "Actualizar Bienes";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2 class="text-center titulo">ActualizarBienes</h2>



@using (Html.BeginForm("BuscarBien","Bienes"))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <h3>Digite numero de patrimonio</h3>
        <div class="col-md-offset-2 col-md-10" >
            <input type="text" name="id" placeholder=@Html.DisplayFor(model => model.numeroDePatrimonio) >
        </div>
        <input type="submit" value="buscar"/>
    </div>
}

@using (Html.BeginForm("ActualizarBienes","Bienes",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.numeroDePatrimonio)

        <div class="form-group">
            @Html.LabelFor(model => model.codigoDeBarras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codigoDeBarras, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.codigoDeBarras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.anadidoPor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.anadidoPor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.anadidoPor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroDeFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroDeFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroDeFactura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ley, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ley, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ley, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.idEspecialidad, "Especialidad", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.idEspecialidad, new { htmlAttributes = new { @class = "form-control" } })*@
                
                @Html.DropDownList("IDEspecialidad")
                @*@Html.ValidationMessageFor(model => model.idEspecialidad, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, "Estado del bien", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.estado,
                                       new SelectList(Enum.GetValues(typeof(EstadosEnum))),
                                       "Selecciona Estado")
                @Html.ValidationMessageFor(model => model.estado, "*", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.condicion, "Condicion del bien(Si esta activo o de baja)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.condicion,
                                       new SelectList(Enum.GetValues(typeof(CondicionesEnum))),
                                       "Selecciona Condicion")
                @Html.ValidationMessageFor(model => model.condicion, "*Obligatorio", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "VerBienes")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inventario/Views/Bienes/AnadirBienes.cshtml
@using System.Web.UI.WebControls;
@using Inventario.Models;
@model Inventario.Models.Bienes
@{
    ViewBag.Title = "Anadir Bienes";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}
   <h2 class="text-center titulo">AnadirBienes</h2>
   

    @using (Html.BeginForm("AnadirBienes", "Bienes", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <p>Digite los datos requeridos</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.numeroDePatrimonio,"Numero de Patrimonio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroDePatrimonio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroDePatrimonio, "*Obligatorio", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group">
          @Html.LabelFor(model => model.codigoDeBarras, htmlAttributes: new { @class = "control-label col-md-2" })
          <div class="col-md-10">
            @Html.EditorFor(model => model.codigoDeBarras, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codigoDeBarras, "*", new { @class = "text-danger" })
           </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "*", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ley, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ley, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ley, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serie, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.idEspecialidad, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
               
                @Html.DropDownList("IDEspecialidad")        
    
                 @*@Html.EditorFor(model => model.idEspecialidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idEspecialidad, "*", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ubicacion, "*", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado,"Estado del bien", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor( model => model.estado,
                                       new SelectList(Enum.GetValues(typeof(EstadosEnum))),
                                       "Selecciona Estado")
                @Html.ValidationMessageFor(model => model.estado, "*", new { @class = "text-danger" })
            </div>
         </div>
         
        <div class="form-group">
                @Html.LabelFor(model => model.condicion,"Condicion del bien", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.condicion,
                                       new SelectList(Enum.GetValues(typeof(CondicionesEnum))),
                                       "Selecciona Condicion")
                    @Html.ValidationMessageFor(model => model.condicion, "*Obligatorio", new { @class = "text-danger" })
                </div>
         </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroDeFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroDeFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroDeFactura, "*Obligatorio", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Anadir" class="btn btn-default" />
            </div>
        </div>
   </div>
}

<div>
    @Html.ActionLink("Ver Bienes", "VerBienes")
</div>

Inventario/Views/Bienes/DarBaja.cshtml
@*@model List<Inventario.Models.Bienes>*@
@model List<Inventario.Models.Bienes>
@{
    ViewBag.Title = "Dar de Baja";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2 class="text-center titulo">Dar de baja bienes</h2>
<h3>Busque los objetos a dar de baja</h3>
@using (Html.BeginForm("BuscarDarBaja","Bienes"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <h3>Digite numero de patrimonio</h3>
        <div class="col-md-offset-2 col-md-10">
            <input type="text" name="id">
        </div>
        <input type="submit" value="Buscar" />
    </div>
}

<h3>Bienes a dar de baja:</h3>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>Numero de patrimonio</th>
                <th>Codigo de Barras</th>
                <th>Descripcion</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Serie</th>
                <th>Ubicacion</th>
                <th>Estado</th>
                <th>Condicion</th>
                <th>Numero de factura</th>
            </tr>
        </thead>
        <tbody>
              
            @if(Model == null)
            {
                <tr><td align="center" colspan="10">Aun no se han anadido objetos</td></tr>
            }
            else
            {
                @*<tr><td>Se puede tirar el modelo</td></tr>*@
            foreach (var item in Model)
            {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.numeroDePatrimonio)</td>
                        <td>@Html.DisplayFor(modelItem => item.codigoDeBarras)</td>
                        <td>@Html.DisplayFor(modelItem => item.descripcion)</td>
                        <td>@Html.DisplayFor(modelItem => item.marca)</td>
                        <td>@Html.DisplayFor(modelItem => item.modelo)</td>
                        <td>@Html.DisplayFor(modelItem => item.serie)</td>
                        <td>@Html.DisplayFor(modelItem => item.ubicacion)</td>
                        <td>@Html.DisplayFor(modelItem => item.estado)</td>
                        <td>@Html.DisplayFor(modelItem => item.condicion)</td>
                        <td>@Html.DisplayFor(modelItem => item.numeroDeFactura)</td>
                    </tr>
                }
            }  
        </tbody>
    </table>
    @using (Html.BeginForm("DarBaja","Bienes",FormMethod.Post)) {
        @Html.AntiForgeryToken()
        <div class="form-actions">
            <input type="submit" value="Dar de Baja" class="btn-light" /> 
        </div>
    }
</div>

Inventario/Views/Bienes/VerBienes.cshtml
@using Inventario.Models
@model IEnumerable<Inventario.Models.Bienes>

@{
    ViewBag.Title = "Ver Bienes";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

    <h2 class="text-center titulo">Ver Bienes</h2>
<div class="row">
    @using (Html.BeginForm("BuscarVerBienes", "Bienes",FormMethod.Post,new {@class ="form-inline col-7" }))
    {
        <div class="form-group">
            <label>
                Buscar Bien:
                <input type="text" class="" name="id" placeholder="Numero de patrimonio" />
                <input type="submit" value="buscar" class=" " />
            </label>  
        </div>
    }

    @using (Html.BeginForm("RestablecerLista","Bienes"))
    {
        <div class="col-3">
            <input type="submit" value="Reestablecer" class="" />
        </div>
    }
</div>



    <hr />
<div class="row">
    <div class="col-12">
        <table class="table table-striped table-responsive-sm">
            <thead class="table-secondary border-bottom">
                <tr>
                    <td>Número de patrimonio</td>
                    <td>Código de Barras</td>
                    <td>Descripción</td>
                    <td>Marca</td>
                    <td>Modelo</td>
                    <td>Serie</td>
                    <td>Ley que financia</td>
                    <td>Ubicacion</td>
                    <td>Especialidad</td>
                    <td>Estado</td>
                    <td>Condicion</td>
                    <td>Número de factura</td>
                    <td>Añadido por</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.numeroDePatrimonio)</td>
                        <td>@Html.DisplayFor(modelItem => item.codigoDeBarras)</td>
                        <td>@Html.DisplayFor(modelItem => item.descripcion)</td>
                        <td>@Html.DisplayFor(modelItem => item.marca)</td>
                        <td>@Html.DisplayFor(modelItem => item.modelo)</td>
                        <td>@Html.DisplayFor(modelItem => item.serie)</td>
                        <td>@Html.DisplayFor(modelItem => item.ley)</td>
                        <td>@Html.DisplayFor(modelItem => item.ubicacion)</td>
                        <td>@Html.DisplayFor(modelItem => item.Especialidad.nombreEspecialidad)</td>
                        <td>@Html.DisplayFor(modelItem => item.estado)</td>
                        <td>@Html.DisplayFor(modelItem => item.condicion)</td>
                        <td>@Html.DisplayFor(modelItem => item.numeroDeFactura)</td>
                        <td>@Html.DisplayFor(modelItem => item.anadidoPor)</td>
                    </tr>
                    }
            </tbody>
        </table>
    </div> 

</div>